### ISSUE TITLE
Add an "About" page

### ISSUE THREAD

**Issue by dsclassen** [bl1231/bilbomd-ui#225]
I think this could probably just point to the Welcome component.

**Comment by shrprabh** [comment]
Hi @dsclassen , is this feature implemented? Can I take it along with the unit testing?

**Comment by dsclassen** [comment]
Sure. The `Home` component is pretty good in terms of content for an `About`  page, but currently is only visible for users that are not logged in. Maybe you could figure out how to repurpose it? or revisit the logic I have implemented that forwards authenticated users to the `Welcome` component?

**Comment by shrprabh** [comment]
Sure, i will look into this and come up with a logic.
