### ISSUE TITLE
Unit testing on BilboMD UI

### ISSUE THREAD

**Issue by shrprabh** [bl1231/bilbomd-ui#754]
**Issue Description:**

The complete unit test coverage for UI from Bilbomd has to be done with **Vitest**, which includes testing on the core areas, namely, **features**, **routes, and layout** components. Testing the routes one after another will ensure that valid UI layouts have been rendered. Perform quality tests of component behavior, events, and the integration of main UI elements. This task also requires structured and modular test cases to let best practices assure maintainable and reliable test coverage.

**Comment by dsclassen** [comment]
Please look at changes I am working on in `fix-vitest-warnings` branch

**Comment by shrprabh** [comment]
I will be in sync. thank you @dsclassen
